### ISSUE TITLE
Inventory for Glider lightweighting

### ISSUE THREAD

**Issue by A-Sterni** [romainsacchi/carculator_utils#2]
According to the documentation (https://carculator.readthedocs.io/en/latest/modeling.html#light-weighting), 3.57 kg of steel are replaced by 0.8 kg aluminium and 1.76 AHSS. In the documentation, it is also mentioned that AHSS is represented by conventional steel. However, in the file "A_matrix.csv" no AHSS or conventional steel is considered. According to this file, 0.8 kg aluminium replace 3.57 kg steel.

**Comment by romainsacchi** [comment]
The input of 1.77 kg AHSS was indeed missing, only the input of 0.8 kg of Al was present. It is now added as an input of regular steel, but it is deducted from the 3.57 kg of steel saved (since the same dataset is used). Hence it shows instead now as -3.57 + 1.77 = -1.8 kg of steel saved.
