### ISSUE TITLE
Results do not change when changing background scenarios

### ISSUE THREAD

**Issue by romainsacchi** [romainsacchi/carculator_utils#5]
When we do change the climate target for the IAM in InventoryCar, results remain unchanged.
 
`ic = InventoryCar(cm, method="recipe", scenario="SSP2-PkBudg1150", indicator="midpoint")`

**Comment by A-Sterni** [comment]
I could not reproduce the error. I get different results for the 3 scenarios (SSP2-NPi, SSP2-PkBudg1150, SSP2-PkBudg500).

I calculated climate change based on Recipe Midpoint for 2030 (for BEV and ICEV-d, medium size).

**Comment by romainsacchi** [comment]
@A-Sterni It's an issue I got reported by a user. I'm anyway rewriting that part entirely, updating most foreground and background inventories (incl. switch to ecoinvent 3.9). I will come back to you with an early version later this week, if you agree to test it out.

**Comment by romainsacchi** [comment]
This is now fixed with `carculator_utils 1.2.0.dev6`
