### ISSUE TITLE
Simultaneous calculation for PHEV-p and PHEV-d is not possible

### ISSUE THREAD

**Issue by A-Sterni** [romainsacchi/carculator_utils#7]
If PHEV-d and PHEV-p are considered simultaneously with the "scope" parameter in the "CarModel", calculation is not possible. If PHEV-d and PHEV-p are considered separately, it works. It also works if "scope" is not used.

I used the newst version (but the problem existed already in older versions) and tried a calculation for 2030.

I think the probem is in: carculator_utils\model.py:728, in VehicleModel.set_share_recuperated_energy(self)
<img width="469" alt="Error" src="https://github.com/romainsacchi/carculator_utils/assets/151236706/fb7642e8-e84f-4631-93ed-a9fe4b3a7e98">

**Comment by A-Sterni** [comment]
The problem is caused by this:
https://github.com/romainsacchi/carculator_utils/blob/418cf965e3ab4be9f6aaeaa245a42891ce078441/carculator_utils/array.py#L66-L69

For me it worked if I changed the code to the following:
```ruby
for missing_pwt in missing_pwts:
    if missing_pwt[0] in scope["powertrain"]:
        for p in missing_pwt[1:]:
            if not p in scope["powertrain"]:
                 scope["powertrain"].append(p)
```

**Comment by romainsacchi** [comment]
Fixed with https://github.com/romainsacchi/carculator_utils/commit/1a59b7083fdb1990782f3848539a372fe122c3a1
