### ISSUE TITLE
Recuperated energy for vehicles with ICE

### ISSUE THREAD

**Issue by A-Sterni** [romainsacchi/carculator_utils#8]
I was wondering why the fuel consumption of ICEV and HEV is so similar. Thus, I had a closer look at the energy consumption model.

If I understand it correct, the recuperated energy is subtracted from the "motive energy". But shouldn't it be subtracted from the "motive energy at wheels" because the recuperated energy can be more or less directly used for propulsion.
![image](https://github.com/romainsacchi/carculator_utils/assets/151236706/4b78d571-4a67-4e02-a018-278590cc8381)

**Comment by romainsacchi** [comment]
Hi @A-Sterni,

If I remember correctly, the idea is that the energy the vehicle recuperates through the mechanical transmission (incl. transmission loss) is stored in a battery (incl. battery charge loss). It is then taken out (incl. battery discharge loss) to power an electric motor that assists the combustion engine.

It usually reduces the energy consumption by 15-25%, but it strongly depends on the driving cycle. Which driving cycle have you used here?

**Comment by A-Sterni** [comment]
Hi Romain,
maybe the graph can explain the problem better than words. I my opinion the current approach is not correct for vehicles with an internal combustion engine because the "recuperated energy" and the "motive energy" are not calculated at the same point of the  drivetrain.
![image](https://github.com/romainsacchi/carculator_utils/assets/151236706/b7797376-ab40-4550-8d0f-692a47356d60)

**Comment by A-Sterni** [comment]
Hi Romain,
please find my suggestion here: https://github.com/romainsacchi/carculator/pull/36

**Comment by romainsacchi** [comment]
Thanks. This is now merged and will be released as `carculator_utils 1.2.0`.

**Comment by A-Sterni** [comment]
In the current version, the engine efficiency and transmission efficiency of the vehicle itself (e.g. HEV if HEV is considered) is used in the numerator to calculated the "saved_TtW_energy_by_recuperation". However, it should be the engine efficiency and transmission efficiency of an electric vehicle.
In my previous pull request, I suggest to use the engine efficiency and transmission efficiency of a BEV. However, this causes an error if no BEV is considered in the scope.
Thus, I would suggest to use the engine efficiency and transmission efficiency of a PHEV-e and make sure that a PHEV-e is always considered in the scope.

An alternative would be to introduce new parameters for the electric engine and electric transmission efficiency of hybrid vehicles.
